spring:
  application:
    name: app1

server:
  servlet:
    context-path: /app1
  port: 8081

cas:
  server-url-prefix: https://kjs.szse.cn:8080/cas
  server-login-url: https://kjs.szse.cn:8080/cas/login
  client-host-url: http://kjs.szse.cn:8081/app1/test/get

eureka:
  client:
    enabled: true
    disable-delta: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    prefer-same-zone-eureka: true
    service-url:
      defaultZone: http://kjs.szse.cn:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    metadata-map:
      zone: 'ft'
      type: service
      cluster: 'kjs'
      group: 'app1'
      serviceName: 'kjs-app1'
      resourceCode: '1'
      version: 1.0
      appHome: 'pwd'
      logHome: 'pwd'
      registe: automatic